### ISSUE TITLE
Unable to build demo

### ISSUE THREAD

**Issue by joshf** [BlackSharkTech/xavier-demo-ios#1]
Hi,

I am trying to build the demo (xcode 10.1), but I receive the error:

Use of undeclared type 'XavierScannerDelegate'

I followed the instructions, tried to remove and re-add the framework but unable to get it to work

**Comment by woosanghun** [comment]
Hi Josh, 

The iOS developers that worked on this are not immediately available, but I talked to one of them and he said that loading frameworks into XCode has been problematic and rarely works the first time.  

The problem could be due to a number of things but he suspects, the framework was added incorrectly, or accidentally left off of the list of compiled sources somehow.

Can you please review your setup.  If you are still stuck, we may have to setup a GotoMeeting session so we can see what is going on there.  

Thanks,

Simon

**Comment by joshf** [comment]
i figured it out

**Comment by woosanghun** [comment]
Great news - do you know the cause is in case we can document the resolution for others?

**Comment by joshf** [comment]
I was trying to build for the simulator which doesn’t work building for a
real device does
